version: "3"
services:
# "db"というコンテナを定義
  db:
    # MySQLのイメージを指定します
    image: mysql:5.7
    environment:

      MYSQL_ROOT_PASSWORD: 8282daimon
    ports:
      - "4306:3306"

  # ポートはどちらも"3306"でも大丈夫ですが、左側を"4306"と別の番号にすることでSequel ProでデータをDBを確認できるようになります。

# "web"というコンテナを定義
  web:
    build: .
    environment:
      DATABASE_PASSWORD: 8282
    command: rails s -p 3000 -b '0.0.0.0'
    # ローカルのディレクトリをマウント
    ports:
      - "3000:3000"
    volumes:
      - .:/web
    # appコンテナとdbコンテナを連携
    links:
      - db